theme: jekyll-theme-architect

plugins:
  - jekyll-sitemap

title: Yunjia Li's homepage
description: Bookmark this to keep an eye on my project updates!
darkmode: true

# Site settings
project_name: Yunjia Li's website

# gh-pages site subpath
baseurl: "/sample-site"

# Entries for menubar.
# title: caption used for item.
# url: relative path to HTML page.
menubar:
- title: Home
  url: /index.html

