# Site settings
title: Yunjia Li's website
description: Bookmark this to keep an eye on my project updates!
darkmode: true
baseurl: /alv-en.github.io
url: "http://alv-en.github.io"
github_username:  alv-en
timezone: America/New_York


# Build settings
markdown: kramdown
plugins:
  - jekyll-sitemap

